//! Card 53 · Git and pull request: the Changes panel with its AI-drafted
//! commit and ahead / behind row beside the Create PR form. Reproduces
//! `design/src/cards/workbench/53-git-pr.html` at 900×520.

use aui::protocol::{ChangeKind, FileChange};
use aui::workbench::{git_changes, pr_check, pr_form, PrDescription};
use gpui::*;

/// `.grid{grid-template-columns:300px 1fr;gap:16px;max-width:880px}`.
const CHANGES_W: f32 = 300.0;
const GRID_GAP: f32 = 16.0;
const GRID_MAX_W: f32 = 880.0;

fn file(path: &str, change: ChangeKind, added: u32, removed: u32) -> FileChange {
    FileChange { path: path.into(), change, added, removed }
}

/// Builds the card content.
pub fn build(_window: &mut Window, _cx: &mut App) -> AnyElement {
    let files = vec![
        (file("validators.ts", ChangeKind::Modified, 8, 3), true),
        (file("validators.test.ts", ChangeKind::Added, 41, 0), true),
        (file("AddressForm.tsx", ChangeKind::Modified, 2, 1), false),
    ];
    let message = "Validate addresses per country and add CA/GB coverage\n\nReturn a structured result from validateAddress and stop accepting an empty country.";
    let description = vec![
        PrDescription::Text("Awaits schema before backfill and returns a structured result from".into()),
        PrDescription::Mono("validateAddress".into()),
        PrDescription::Text(
            ". Adds regression tests for US ZIP+4, Canadian postal codes and a missing country.\n\nGenerated by Claude Code in worktree".into(),
        ),
        PrDescription::Mono("checkout-flow-v2".into()),
        PrDescription::Text(".".into()),
    ];
    let checks = vec![
        pr_check("ci / unit", true).detail("2 m 10 s"),
        pr_check("ci / e2e", true).running().detail("running"),
        pr_check("lint", true),
    ];

    div()
        .w_full()
        .max_w(px(GRID_MAX_W))
        .flex()
        .flex_row()
        .items_stretch()
        .flex_none()
        .gap(px(GRID_GAP))
        .child(
            div().flex_none().w(px(CHANGES_W)).child(
                git_changes("card53-changes", files, message, 3, 0)
                    .branch("feature/checkout-flow-v2")
                    .on_action(|_, _, _| {}),
            ),
        )
        .child(
            div().flex_1().min_w(px(0.0)).child(
                pr_form("card53-pr", "main", "Validate addresses per country and add CA/GB coverage", description, checks)
                    .provider("GitHub")
                    .issue("Linear ACM-412")
                    .on_action(|_, _, _| {}),
            ),
        )
        .into_any_element()
}
