//! Generates `$OUT_DIR/tokens.rs` from `design/tokens/tokens.json` and
//! `design/tokens/motion.json`. The JSON files are the single source of truth;
//! nothing in the library holds a literal colour, size or duration.
//!
//! Generated items:
//! - `Palette` (one `Hsla` field per colour key, three shadow slices) with
//!   `light()` / `dark()` constructors.
//! - `scale` module: every `shared` metric as a typed const
//!   (`px` values as `f32`, `ms` as `Duration`, ratios as `f32`, easings as
//!   `[f32; 4]`, font families as `&str`).
//! - `springs` module: the four `SpringConfig`s from motion.json.

use serde_json::Value;
use std::{env, fs, path::PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let design = manifest.join("../../design/tokens");
    let tokens_path = design.join("tokens.json");
    let motion_path = design.join("motion.json");
    println!("cargo:rerun-if-changed={}", tokens_path.display());
    println!("cargo:rerun-if-changed={}", motion_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let tokens: Value = serde_json::from_str(&fs::read_to_string(&tokens_path).expect("read tokens.json"))
        .expect("parse tokens.json");
    let motion: Value = serde_json::from_str(&fs::read_to_string(&motion_path).expect("read motion.json"))
        .expect("parse motion.json");

    let mut out = String::new();
    out.push_str("// @generated by aui-tokens/build.rs from design/tokens/*.json. Do not edit.\n\n");
    emit_palette(&mut out, &tokens);
    emit_scale(&mut out, &tokens);
    emit_springs(&mut out, &motion);

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("tokens.rs");
    fs::write(dest, out).expect("write tokens.rs");
}

// ---------------------------------------------------------------------------
// Palette
// ---------------------------------------------------------------------------

fn emit_palette(out: &mut String, tokens: &Value) {
    let light = tokens["light"].as_object().expect("light palette");
    let dark = tokens["dark"].as_object().expect("dark palette");

    let mut colour_keys = Vec::new();
    let mut shadow_keys = Vec::new();
    for (key, value) in light {
        let value = value.as_str().expect("token value is a string");
        if key.starts_with("shadow-") {
            shadow_keys.push(key.clone());
        } else if parse_colour(value).is_some() {
            colour_keys.push(key.clone());
        } else {
            panic!("unrecognised light token {key} = {value}");
        }
    }
    for key in colour_keys.iter().chain(shadow_keys.iter()) {
        assert!(dark.contains_key(key), "dark palette is missing `{key}`");
    }

    out.push_str("/// One layer of a box shadow, in logical pixels.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq)]\n");
    out.push_str("pub struct ShadowLayer {\n    /// Horizontal offset.\n    pub x: f32,\n    /// Vertical offset.\n    pub y: f32,\n    /// Blur radius.\n    pub blur: f32,\n    /// Spread radius.\n    pub spread: f32,\n    /// Shadow colour.\n    pub color: gpui::Rgba,\n}\n\n");

    out.push_str("/// The full colour palette of one theme. Field names mirror the CSS custom\n/// properties in `design/tokens/tokens.css` (`--surface-1` → `surface_1`).\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq)]\n#[allow(missing_docs)]\npub struct Palette {\n");
    for key in &colour_keys {
        out.push_str(&format!("    pub {}: gpui::Hsla,\n", ident(key)));
    }
    for key in &shadow_keys {
        out.push_str(&format!("    pub {}: &'static [ShadowLayer],\n", ident(key)));
    }
    out.push_str("}\n\n");

    out.push_str("impl Palette {\n");
    out.push_str("    /// Names of every colour field, in token order.\n");
    out.push_str("    pub const COLOR_NAMES: &'static [&'static str] = &[\n");
    for key in &colour_keys {
        out.push_str(&format!("        \"{key}\",\n"));
    }
    out.push_str("    ];\n\n");
    out.push_str("    /// Looks a colour up by its token name (`\"surface-1\"`).\n");
    out.push_str("    pub fn color(&self, name: &str) -> Option<gpui::Hsla> {\n        match name {\n");
    for key in &colour_keys {
        out.push_str(&format!("            \"{key}\" => Some(self.{}),\n", ident(key)));
    }
    out.push_str("            _ => None,\n        }\n    }\n");
    out.push_str("}\n\n");

    for (name, map) in [("light", light), ("dark", dark)] {
        out.push_str(&format!("/// The {name} palette.\npub fn {name}() -> Palette {{\n    Palette {{\n"));
        for key in &colour_keys {
            let (r, g, b, a) = parse_colour(map[key].as_str().unwrap()).unwrap();
            out.push_str(&format!(
                "        {}: gpui::Rgba {{ r: {r:?}, g: {g:?}, b: {b:?}, a: {a:?} }}.into(),\n",
                ident(key)
            ));
        }
        for key in &shadow_keys {
            out.push_str(&format!("        {}: &[", ident(key)));
            for layer in parse_shadow(map[key].as_str().unwrap()) {
                let (x, y, blur, spread, (r, g, b, a)) = layer;
                out.push_str(&format!(
                    "ShadowLayer {{ x: {x:?}, y: {y:?}, blur: {blur:?}, spread: {spread:?}, color: gpui::Rgba {{ r: {r:?}, g: {g:?}, b: {b:?}, a: {a:?} }} }}, "
                ));
            }
            out.push_str("],\n");
        }
        out.push_str("    }\n}\n\n");
    }
}

// ---------------------------------------------------------------------------
// Shared scale
// ---------------------------------------------------------------------------

fn emit_scale(out: &mut String, tokens: &Value) {
    let shared = tokens["shared"].as_object().expect("shared tokens");
    out.push_str("/// Shared (theme-independent) metrics: type scale, line heights, spacing,\n/// radii, control heights, durations, easings and font families.\n");
    out.push_str("#[allow(missing_docs)]\npub mod scale {\n    use std::time::Duration;\n\n");
    for (key, value) in shared {
        let value = value.as_str().expect("shared token is a string");
        let name = ident(key).to_uppercase();
        if key.starts_with("spring-") || value.starts_with("var(") {
            continue; // springs come from motion.json; `st-*` aliases are resolved in code
        }
        if key.starts_with("font-") {
            let family = value.trim_start_matches('"');
            let family = &family[..family.find('"').expect("quoted family")];
            out.push_str(&format!("    pub const {name}: &str = {family:?};\n"));
        } else if let Some(ms) = value.strip_suffix("ms") {
            let ms: u64 = ms.parse().expect("ms value");
            out.push_str(&format!("    pub const {name}: Duration = Duration::from_millis({ms});\n"));
        } else if let Some(px) = value.strip_suffix("px") {
            let px: f32 = px.parse().expect("px value");
            out.push_str(&format!("    pub const {name}: f32 = {px:?};\n"));
        } else if let Some(em) = value.strip_suffix("em") {
            let em: f32 = em.parse().expect("em value");
            out.push_str(&format!("    pub const {name}_EM: f32 = {em:?};\n"));
        } else if let Some(inner) = value.strip_prefix("cubic-bezier(") {
            let nums: Vec<f32> = inner
                .trim_end_matches(')')
                .split(',')
                .map(|n| n.trim().parse().expect("bezier number"))
                .collect();
            assert_eq!(nums.len(), 4, "cubic-bezier needs 4 numbers");
            out.push_str(&format!(
                "    pub const {name}: [f32; 4] = [{:?}, {:?}, {:?}, {:?}];\n",
                nums[0], nums[1], nums[2], nums[3]
            ));
        } else if let Ok(ratio) = value.parse::<f32>() {
            out.push_str(&format!("    pub const {name}: f32 = {ratio:?};\n"));
        } else {
            panic!("unrecognised shared token {key} = {value}");
        }
    }
    out.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Springs
// ---------------------------------------------------------------------------

fn emit_springs(out: &mut String, motion: &Value) {
    let springs = motion["springs"].as_object().expect("springs");
    out.push_str("/// The four springs from `design/tokens/motion.json` (stiffness / damping / mass).\n");
    out.push_str("pub mod springs {\n    use gpui::SpringConfig;\n\n");
    for (key, spec) in springs {
        let k = spec["stiffness"].as_f64().unwrap() as f32;
        let d = spec["damping"].as_f64().unwrap() as f32;
        let m = spec["mass"].as_f64().unwrap() as f32;
        let usage = spec["use"].as_str().unwrap_or("");
        out.push_str(&format!(
            "    /// `{key}` spring — {usage}.\n    pub const {}: SpringConfig = SpringConfig::new({k:?}, {d:?}, {m:?});\n",
            key.to_uppercase()
        ));
    }
    out.push_str("}\n\n");

    let durations = motion["durations_ms"].as_object().expect("durations");
    out.push_str("/// Motion durations from `motion.json`, mirrored for convenience.\n#[allow(missing_docs)]\npub mod durations {\n    use std::time::Duration;\n\n");
    for (key, ms) in durations {
        out.push_str(&format!(
            "    pub const {}: Duration = Duration::from_millis({});\n",
            key.to_uppercase(),
            ms.as_u64().unwrap()
        ));
    }
    out.push_str("}\n");
}

// ---------------------------------------------------------------------------
// Parsing helpers
// ---------------------------------------------------------------------------

fn ident(key: &str) -> String {
    key.replace('-', "_")
}

/// Parses `#RRGGBB`, `#RRGGBBAA` or `rgba(r,g,b,a)` into 0..1 components.
fn parse_colour(value: &str) -> Option<(f32, f32, f32, f32)> {
    let value = value.trim();
    if let Some(hex) = value.strip_prefix('#') {
        let n = u32::from_str_radix(hex, 16).ok()?;
        return match hex.len() {
            6 => Some((
                ((n >> 16) & 0xff) as f32 / 255.0,
                ((n >> 8) & 0xff) as f32 / 255.0,
                (n & 0xff) as f32 / 255.0,
                1.0,
            )),
            8 => Some((
                ((n >> 24) & 0xff) as f32 / 255.0,
                ((n >> 16) & 0xff) as f32 / 255.0,
                ((n >> 8) & 0xff) as f32 / 255.0,
                (n & 0xff) as f32 / 255.0,
            )),
            _ => None,
        };
    }
    if let Some(inner) = value.strip_prefix("rgba(").or_else(|| value.strip_prefix("rgb(")) {
        let parts: Vec<f32> = inner
            .trim_end_matches(')')
            .split(',')
            .map(|p| p.trim().parse::<f32>().ok())
            .collect::<Option<_>>()?;
        return match parts.len() {
            3 => Some((parts[0] / 255.0, parts[1] / 255.0, parts[2] / 255.0, 1.0)),
            4 => Some((parts[0] / 255.0, parts[1] / 255.0, parts[2] / 255.0, parts[3])),
            _ => None,
        };
    }
    None
}

type Layer = (f32, f32, f32, f32, (f32, f32, f32, f32));

/// Parses a CSS `box-shadow` list such as
/// `0 4px 14px rgba(20,22,30,.10),0 1px 2px rgba(20,22,30,.06)`.
fn parse_shadow(value: &str) -> Vec<Layer> {
    // Split on commas that are not inside parentheses.
    let mut layers = Vec::new();
    let mut depth = 0;
    let mut start = 0;
    let bytes = value.as_bytes();
    for (i, &b) in bytes.iter().enumerate() {
        match b {
            b'(' => depth += 1,
            b')' => depth -= 1,
            b',' if depth == 0 => {
                layers.push(&value[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }
    layers.push(&value[start..]);

    layers
        .into_iter()
        .map(|layer| {
            let layer = layer.trim();
            let colour_at = layer.find("rgb").expect("shadow colour");
            let colour = parse_colour(&layer[colour_at..]).expect("shadow colour parses");
            let nums: Vec<f32> = layer[..colour_at]
                .split_whitespace()
                .map(|n| n.trim_end_matches("px").parse::<f32>().expect("shadow length"))
                .collect();
            let x = nums.first().copied().unwrap_or(0.0);
            let y = nums.get(1).copied().unwrap_or(0.0);
            let blur = nums.get(2).copied().unwrap_or(0.0);
            let spread = nums.get(3).copied().unwrap_or(0.0);
            (x, y, blur, spread, colour)
        })
        .collect()
}
