//! Build script for `aui-icons`.
//!
//! Reads the design system sprite sheet (`design/src/sprite.svg`), splits every
//! `<symbol id="...">` into a standalone SVG file under `$OUT_DIR/icons/`, and
//! generates `$OUT_DIR/icons.rs` with the `IconName` enum plus a `lookup`
//! function over the generated bytes.
//!
//! gpui rasterises an SVG into an alpha mask that is tinted with the element's
//! text colour, and it ignores CSS classes, so the generated files carry
//! explicit `stroke` / `fill` presentation attributes rather than relying on
//! the `.i` rules in `design/src/base.css`.

use std::{collections::BTreeSet, env, fs, path::PathBuf};

/// Header applied to every generated standalone icon file.
const SVG_OPEN: &str = concat!(
    r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" "#,
    r##"stroke="#000" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">"##
);

fn main() {
    let sprite_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../design/src/sprite.svg");
    println!("cargo:rerun-if-changed={}", sprite_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let sprite = fs::read_to_string(&sprite_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", sprite_path.display()));

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let icons_dir = out_dir.join("icons");
    fs::create_dir_all(&icons_dir).expect("create $OUT_DIR/icons");

    let symbol = regex::Regex::new(r#"(?s)<symbol\s+id="([^"]+)"[^>]*>(.*?)</symbol>"#)
        .expect("valid symbol regex");

    let mut ids = BTreeSet::new();
    let mut symbols: Vec<(String, String)> = Vec::new();
    for caps in symbol.captures_iter(&sprite) {
        let id = caps[1].to_string();
        let inner = caps[2].replace(r#"fill="currentColor""#, r##"fill="#000""##);
        assert!(
            ids.insert(id.clone()),
            "duplicate symbol id `{id}` in sprite"
        );
        symbols.push((id, inner));
    }
    assert!(!symbols.is_empty(), "no <symbol> elements found in sprite");

    let mut variants = String::new();
    let mut all = String::new();
    let mut id_arms = String::new();
    let mut path_arms = String::new();
    let mut bytes_arms = String::new();
    let mut lookup_arms = String::new();

    for (id, inner) in &symbols {
        let file = icons_dir.join(format!("{id}.svg"));
        // `.fic` (file-type) glyphs are stroked at 1.5 in base.css, `.i` at 1.6.
        let open = if id.starts_with("ft-") { SVG_OPEN.replace("stroke-width=\"1.6\"", "stroke-width=\"1.5\"") } else { SVG_OPEN.to_string() };
        fs::write(&file, format!("{open}{inner}</svg>"))
            .unwrap_or_else(|e| panic!("failed to write {}: {e}", file.display()));

        let variant = pascal_case(id);
        let path = format!("icons/aui/{id}.svg");
        let include = format!(r#"include_bytes!(concat!(env!("OUT_DIR"), "/icons/{id}.svg"))"#);

        variants.push_str(&format!(
            "    /// The `{id}` glyph from the design sprite.\n"
        ));
        variants.push_str(&format!("    {variant},\n"));
        all.push_str(&format!("    IconName::{variant},\n"));
        id_arms.push_str(&format!("            IconName::{variant} => \"{id}\",\n"));
        path_arms.push_str(&format!("            IconName::{variant} => \"{path}\",\n"));
        bytes_arms.push_str(&format!("            IconName::{variant} => {include},\n"));
        lookup_arms.push_str(&format!("        \"{path}\" => Some({include}),\n"));
    }

    let generated = format!(
        r##"// @generated by build.rs from design/src/sprite.svg — do not edit.

/// Every glyph in the Agentic UI sprite sheet.
///
/// One variant per `<symbol id="...">` in `design/src/sprite.svg`; the sprite
/// id is available through [`IconName::id`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IconName {{
{variants}}}

impl IconName {{
    /// Every glyph, in sprite order.
    pub const ALL: &'static [IconName] = &[
{all}    ];

    /// The `id` of this glyph's `<symbol>` in the sprite sheet.
    pub fn id(self) -> &'static str {{
        match self {{
{id_arms}        }}
    }}

    /// The asset path this glyph is served at by [`crate::Assets`].
    pub fn path(self) -> &'static str {{
        match self {{
{path_arms}        }}
    }}

    /// The standalone SVG bytes for this glyph.
    pub fn bytes(self) -> &'static [u8] {{
        match self {{
{bytes_arms}        }}
    }}
}}

/// Resolve an `icons/aui/<id>.svg` asset path to its SVG bytes.
pub fn lookup(path: &str) -> Option<&'static [u8]> {{
    match path {{
{lookup_arms}        _ => None,
    }}
}}
"##
    );

    fs::write(out_dir.join("icons.rs"), generated).expect("write $OUT_DIR/icons.rs");
}

/// Convert a sprite id (`ft-folder-open`) to a Rust variant name (`FtFolderOpen`).
fn pascal_case(id: &str) -> String {
    id.split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
